version: "3.7"

services:
  app:
    container_name: "sv-frontend-test"
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: sh entrypoint.sh
    volumes:
      - "./output:/usr/app/reports/report"
networks:
  default:
    external:
      name: arbocontrol-docker-testes_sv-network
